### ISSUE TITLE
It doesn't seem to patch.

### ISSUE THREAD

**Issue by Pretendolover3** [PretendoNetwork/nimbus#13]
I'm on Luma 12.0.0, I tried patching it, but it seems to be stuck on the "Nintendo" option. Can somebody please help?

**Comment by WaitlistedJay** [comment]
Same issue here

**Comment by WaitlistedJay** [comment]
#10

**Comment by jonbarrow** [comment]
Luma 13 is now released and is the recommended way to use Nimbus. Please update to the latest Luma version and update the patches with the latest release, as well as install the Nimbus CIA. All other versions of the patches should be considered deprecated now
