### ISSUE TITLE
Add LUMA3DS 13 Support

### ISSUE THREAD

**Issue by Idontcode123** [PretendoNetwork/nimbus#17]
pls add luma3ds

**Comment by TraceEntertains** [comment]
there's already a pr, jon just needs to review it

**Comment by EpicDoodleboy2** [comment]
> pls add luma3ds

If you really want to follow this
https://github.com/PretendoNetwork/nimbus/issues/10

**Comment by jonbarrow** [comment]
Luma 13 support has been merged
