### ISSUE TITLE
Fix Flipnote Studio DSi crashing with nimbus

### ISSUE THREAD

**Issue by Idontcode123** [PretendoNetwork/nimbus#18]

**Comment by jonbarrow** [comment]
Nimble is our legacy, deprecated, WiiU patcher. I assume you mean't Nimbus? If you did mean Nimble, then we no longer support that app, and you made this issue on the wrong repository

If you did mean Nimbus, then ensure you have the latest version of both Luma and Nimbus installed, as well as the latest IPS patches

Also when making an issue report, please provide more information on what is actually going wrong and information about your environment, as well as some steps to reproduce.

**Comment by TraceEntertains** [comment]
I would like to keep as few issues open as possible, could you please provide more information on the issue so i can look into it?
