### ISSUE TITLE
[Feature Request] Swap between rverse and juxt when moving between nintendo and pretendo accounts

### ISSUE THREAD

**Issue by dimaguy** [PretendoNetwork/nimbus#21]
Would it be possible to just swap the patch files on the luma folder when moving back to the nintendo account?

**Comment by TraceEntertains** [comment]
We were thinking about doing this, but it seemed like a very half-baked solution, so we didn't 

On the other hand, I'm looking into making a version of the miiverse patch that functions as both an rverse and pretendo patch, so no file swapping

**Comment by dimaguy** [comment]
> We were thinking about doing this, but it seemed like a very half-baked solution, so we didn't 
> 
> On the other hand, I'm looking into making a version of the miiverse patch that functions as both an rverse and pretendo patch, so no file swapping

I think it's fine if you manage to build the files in the cia binary, it hides the clutter on the end user.
Making the miiverse patch that handles both at the same time would require a fair bit more logic(and dev pain. Because it's not just changing a url, it's building in a selector menu at some point likely in assembly) that you probably don't need to go through

**Comment by TraceEntertains** [comment]
jon mentioned not wanting to do something like that mainly due to sd card wear from repeated copying of files, which is understandable somewhat, I wouldn't call it a major concern, but after all, it is patches for servers he created, so final decision is up to him (also because he is the only person other than shutterbug with merge permissions)

**Comment by dimaguy** [comment]
> jon mentioned not wanting to do something like that mainly due to sd card wear from repeated copying of files, which is understandable somewhat, I wouldn't call it a major concern, but after all, it is patches for servers he created a lot of, so final decision is up to him (also because he is the only person other than shutterbug with merge permissions)

Well that's right, it would cause extra sd card wear, hence it could be made an optional toggle as well. However I don't think people are changing that much between accounts for it to become a threat(we can slap a warning on it too), and nevertheless the process without this feature request going through is already pretty much the same, just manual, so the wear damage is not yet avoidable.

An alternative could be to implement banking of patches on luma, but that's severely overkill

**Comment by LeTak0** [comment]
> Would it be possible to just swap the patch files on the luma folder when moving back to the nintendo account?

On the Pretendo Discord you can search for rv2juxt, it is a sysmodul to switch between rverse and juxt depending on the environment you selected in nimbus.
[rv2juxt.zip](https://github.com/PretendoNetwork/nimbus/files/14786889/rv2juxt.zip)

**Comment by jonbarrow** [comment]
Closing as rverse is, effectively, shutting down and even if it wasn't it's a totally different service. Adding support for it in our upstream patches is out of scope for us
