### ISSUE TITLE
[Feature]: Cross-platform (NN and PN) friending

### ISSUE THREAD

**Issue by Susposter779** [PretendoNetwork/nimbus#50]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

I want to be able to go into Add Friends on either the Wii U or 3DS and input a friend code belonging to a Nintendo Network user

### Why do you want to have this feature?

I want to be able to friend someone who is still on the vanilla Nintendo Network.

**Comment by ProjectDreadman** [comment]
I don’t think that this will be possible because they don’t have access to friend codes or NN IDs on Nintendo side

**Comment by jonbarrow** [comment]
This is not possible. Nintendo Network and Pretendo Network are separate services
