### ISSUE TITLE
Doesn't patch

### ISSUE THREAD

**Issue by guusbuk** [PretendoNetwork/nimbus#8]
Using a N3DSXL on latest luma, OFW, and nimbus version.
Luma patches are turned on.

When i press Pretendo in the Nimbus patcher, the system restarts, but i am still connected to Nintendo. When i open Nimbus again it still says Nintendo loaded. I did have the same problem with the other beta, but never got to fix it.

**Comment by TheGitGubGuy** [comment]
Same problem here

**Comment by danilacasito** [comment]
Same Problem Here

**Comment by KalFox** [comment]
Yeah, I've been having the same issue with my new 3dsXL as well. Was really looking forward to it.

**Comment by Linx-ESP** [comment]
As per https://github.com/PretendoNetwork/nimbus/pull/6/commits/ce4b54d8096d801674f37c8c08b631cbb4b961a2
`Ensure Game Patching is enabled in Luma3DS settings (hold SELECT at boot to enter Luma settings)`

**Comment by danilacasito** [comment]
Mine IS ENABLED

**Comment by guusbuk** [comment]
> As per [ce4b54d](https://github.com/PretendoNetwork/nimbus/commit/ce4b54d8096d801674f37c8c08b631cbb4b961a2) `Ensure Game Patching is enabled in Luma3DS settings (hold SELECT at boot to enter Luma settings)`

This setting is enabled. Sometimes it works now, but most of the time it stays at Nintendo.

**Comment by Hazuki81** [comment]
Worked just fine with Luma3DS 11.0, but now on Luma3DS 12.0 it stays on Nintendo Network. Game pathching is enabled, but no matter what it just stays on Nintendo Network

**Comment by Linkdash2019** [comment]
I am too stuck on Nintendo network only thing that changed is that my friend list got new save data (aka deleted friends and redid tutorial)

**Comment by EpicDoodleboy2** [comment]
> I am too stuck on Nintendo network only thing that changed is that my friend list got new save data (aka deleted friends and redid tutorial)

Apparently the friend server is stuck on pretendo

**Comment by Linkdash2019** [comment]
I just friended a non-homebrewed 3ds (without pretendo) while my friend list was in pretendo mode

**Comment by EpicDoodleboy2** [comment]
> Using a N3DSXL on latest luma, OFW, and nimbus version. Luma patches are turned on.
> 
> When i press Pretendo in the Nimbus patcher, the system restarts, but i am still connected to Nintendo. When i open Nimbus again it still says Nintendo loaded. I did have the same problem with the other beta, but never got to fix it.

Hey you gonna have to downgrade your Luma version to ver 11.00 to get pretendo to work because when they were using nimbus They used Luma 11.00 and nimbus came out in January before Luma version 12.00 (Latest version) that came out in February.

**Comment by EpicDoodleboy2** [comment]
> I just friended a non-homebrewed 3ds (without pretendo) while my friend list was in pretendo mode

So with that conclusion, it says it is on pretendo but it is actually stuck on nintendo or someone had the same friend code as the one that you added.

**Comment by EpicDoodleboy2** [comment]
Also not related but after looking at wii closures and the recent 3ds/wii u closures I might think that nintendo network might close it's doors next year or the year after but this is just speculation...

**Comment by EpicDoodleboy2** [comment]
> I just friended a non-homebrewed 3ds (without pretendo) while my friend list was in pretendo mode

https://github.com/PretendoNetwork/nimbus/issues/10
I found a simple fix

**Comment by jonbarrow** [comment]
Luma 13 is now released and is the recommended way to use Nimbus. Please update to the latest Luma version and update the patches with the latest release, as well as install the Nimbus CIA. All other versions of the patches should be considered deprecated now
