### ISSUE TITLE
Broken with Luma3DS 12

### ISSUE THREAD

**Issue by larb0b** [PretendoNetwork/nimbus#9]
If Luma3DS 12 is installed, then Nimbus never actually switches the active account. After downgrading to Luma3DS 11, it works properly again.

**Comment by EpicDoodleboy2** [comment]
> If Luma3DS 12 is installed, then Nimbus never actually switches the active account. After downgrading to Luma3DS 11, it works properly again.

I have Luma 3DS 12.00 and I was very confused how it didn't switch but when you said that you downgraded to 11.00 and it worked, Then it seems nimbus needs updating for compatibility for luma 12.00. That includes the friend server but that is stuck on pretendo instead.

**Comment by EpicDoodleboy2** [comment]
> > If Luma3DS 12 is installed, then Nimbus never actually switches the active account. After downgrading to Luma3DS 11, it works properly again.
> 
> I have Luma 3DS 12.00 and I was very confused how it didn't switch but when you said that you downgraded to 11.00 and it worked, Then it seems nimbus needs updating for compatibility for luma 12.00. That includes the friend server but that is stuck on pretendo instead.

But then again after nimbus released ver 12.00 of Luma3DS came out so They were testing it out on ver 11.11

**Comment by EpicDoodleboy2** [comment]
> If Luma3DS 12 is installed, then Nimbus never actually switches the active account. After downgrading to Luma3DS 11, it works properly again.

Fixed

> If Luma3DS 12 is installed, then Nimbus never actually switches the active account. After downgrading to Luma3DS 11, it works properly again.

Solution
[](https://github.com/PretendoNetwork/nimbus/issues/10)

**Comment by jonbarrow** [comment]
Luma 13 is now released and is the recommended way to use Nimbus. Please update to the latest Luma version and update the patches with the latest release, as well as install the Nimbus CIA. All other versions of the patches should be considered deprecated now
